//go:build !notuya

package tuya

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// The test vectors in /tmp/tuya_vectors.json are generated by
// tools/tuya/gen_vectors.py using tinytuya itself, so they are ground truth
// for our Go implementation. Regenerate with:
//
//	/tmp/tuya-venv/bin/python tools/tuya/gen_vectors.py > /tmp/tuya_vectors.json
//
// The test skips (not fails) when the file is absent, so CI without the
// python venv stays green.
func loadVectors(t *testing.T) map[string]map[string]interface{} {
	t.Helper()
	b, err := os.ReadFile("/tmp/tuya_vectors.json")
	if err != nil {
		t.Skip("no vectors file, run tools/tuya/gen_vectors.py first")
	}
	var v map[string]map[string]interface{}
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("vectors file broken: %v", err)
	}
	return v
}

func hx(t *testing.T, s string) []byte {
	t.Helper()
	b, err := hex.DecodeString(s)
	if err != nil {
		t.Fatalf("bad hex %q: %v", s, err)
	}
	return b
}

func str(m map[string]interface{}, k string) string {
	s, _ := m[k].(string)
	return s
}

func TestAES(t *testing.T) {
	v := loadVectors(t)
	p := v["ecb_padded"]
	got, err := aesECBEncrypt(hx(t, str(p, "key")), hx(t, str(p, "plain")))
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(got) != str(p, "cipher") {
		t.Errorf("ECB padded mismatch:\n got %x\nwant %s", got, str(p, "cipher"))
	}
	back, err := aesECBDecrypt(hx(t, str(p, "key")), got)
	if err != nil || string(back) != string(hx(t, str(p, "plain"))) {
		t.Errorf("ECB roundtrip failed: %v", err)
	}

	n := v["ecb_nopad"]
	got, err = aesECBEncryptNoPad(hx(t, str(n, "key")), hx(t, str(n, "plain")))
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(got) != str(n, "cipher") {
		t.Errorf("ECB no-pad mismatch:\n got %x\nwant %s", got, str(n, "cipher"))
	}
}

func TestPack55AA(t *testing.T) {
	v := loadVectors(t)
	c := v["frame_55aa_crc"]
	got := pack55AA(1, 0x0a, hx(t, str(c, "payload")), nil)
	if hex.EncodeToString(got) != str(c, "frame") {
		t.Errorf("55AA/CRC frame mismatch:\n got %x\nwant %s", got, str(c, "frame"))
	}
	m := v["frame_55aa_hmac"]
	got = pack55AA(1, 0x0a, hx(t, str(m, "payload")), hx(t, str(m, "key")))
	if hex.EncodeToString(got) != str(m, "frame") {
		t.Errorf("55AA/HMAC frame mismatch:\n got %x\nwant %s", got, str(m, "frame"))
	}
}

func TestUnpack55AA(t *testing.T) {
	v := loadVectors(t)
	m := v["frame_55aa_hmac"]
	msg, err := unpack55AA(hx(t, str(m, "frame")), hx(t, str(m, "key")))
	if err != nil {
		t.Fatal(err)
	}
	if msg.seqno != 1 || msg.cmd != 0x0a {
		t.Errorf("header wrong: %+v", msg)
	}
	if !msg.crcGood {
		t.Error("HMAC check failed on a good frame")
	}
	// The retcode (4 bytes) is part of the payload as packed but is stripped
	// by unpack, exactly like tinytuya does (see the unpack_check vector).
	want := hx(t, str(m, "payload"))[4:]
	if hex.EncodeToString(msg.payload) != hex.EncodeToString(want) {
		t.Errorf("payload mismatch: got %x want %x", msg.payload, want)
	}
}

func TestPackUnpack6699(t *testing.T) {
	v := loadVectors(t)
	f := v["frame_6699"]
	key, iv := hx(t, str(f, "key")), hx(t, str(f, "iv"))
	got, err := pack6699(1, 0x0a, hx(t, str(f, "payload")), key, iv)
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(got) != str(f, "frame") {
		t.Errorf("6699 frame mismatch:\n got %x\nwant %s", got, str(f, "frame"))
	}
	msg, err := unpack6699(hx(t, str(f, "frame")), key)
	if err != nil {
		t.Fatal(err)
	}
	if !msg.crcGood || msg.seqno != 1 || msg.cmd != 0x0a {
		t.Errorf("6699 unpack wrong: %+v", msg)
	}
	if hex.EncodeToString(msg.payload) != str(f, "payload") {
		t.Errorf("6699 payload mismatch: got %x", msg.payload)
	}
}

func TestSessionKeyDerivation(t *testing.T) {
	v := loadVectors(t)
	for _, name := range []string{"session_34", "session_35"} {
		s := v[name]
		key, ln, rn := hx(t, str(s, "key")), hx(t, str(s, "lnonce")), hx(t, str(s, "rnonce"))
		xor := make([]byte, 16)
		for i := range xor {
			xor[i] = ln[i] ^ rn[i]
		}
		var got []byte
		var err error
		if name == "session_34" {
			got, err = aesECBEncryptNoPad(key, xor)
		} else {
			gcm, gerr := newGCM(key)
			if gerr != nil {
				t.Fatal(gerr)
			}
			ct, gerr := gcmEncrypt(gcm, ln[:12], xor, nil)
			if gerr != nil {
				t.Fatal(gerr)
			}
			got, err = ct[:16], gerr
		}
		if err != nil {
			t.Fatalf("%s: %v", name, err)
		}
		if hex.EncodeToString(got) != str(s, "session") {
			t.Errorf("%s mismatch: got %x want %s", name, got, str(s, "session"))
		}
	}
}

func TestStep2Decrypt(t *testing.T) {
	v := loadVectors(t)
	s := v["step2_34"]
	key := hx(t, "30313233343536373839616263646566")
	got, err := aesECBDecrypt(key, hx(t, str(s, "cipher")))
	if err != nil {
		t.Fatal(err)
	}
	if hex.EncodeToString(got) != str(s, "plain") {
		t.Errorf("step2 decrypt mismatch:\n got %x\nwant %s", got, str(s, "plain"))
	}
}

func TestPropsFromDPS(t *testing.T) {
	dps := map[string]interface{}{"1": false, "6": 59.0, "7": 22.0, "99": "unknown"}
	props := propsFromDPS(dps, defaultDPSNames)
	if props["humidity"] != 59.0 || props["temperature"] != 22.0 || props["switch"] != false {
		t.Errorf("mapping wrong: %v", props)
	}
	if _, ok := props["99"]; ok {
		t.Error("unmapped dps leaked into props")
	}
}
