name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.24

    - name: Make freepsd-light
      run: make build/freepsd-light

    - name: Build
      run: go build -tags=nomuteme -v ./...

    - name: Test
      run: go test -tags=nomuteme  -v ./...